version: '3.8'

services:
  web:
    build: .
    command: bash -c "./entrypoint.sh"
    volumes:
      - .:/app
      - ./library/fixtures:/app/library/fixtures
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_library.settings
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/library_db
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
